remove per-simulator flist files, adding static compile args to templates
Lightelligence/rules_verilog pull request #33
Opened 2022-10-13 14:25 UTC by jmlemay99

- transitive flist generation will now generate one file per package, not two (one per simulator)
- added static compile args to vendor compile templates

2022-10-18 04:17 UTC, ciglass requested changes

2022-10-18 04:17 UTC, ciglass commented on vendors/cadence/verilog_dv_tb_compile_args.f.template
> +-sv
@jmlemay99 why are all these new flags necessary? How does the compile flow work without these?

2022-10-18 04:17 UTC, ciglass commented on vendors/synopsys/verilog_dv_default_sim_opts.f
> +-full64
@jmlemay99 same question as before: why are all these new flags necessary? How does the compile flow work without these?

2022-10-18 04:17 UTC, ciglass commented on vendors/synopsys/verilog_dv_tb_compile_args.f.template
> +-sverilog
@jmlemay99 same question as before: why are all these new flags necessary? How does the compile flow work without these?

2022-10-18 04:17 UTC, ciglass commented on vendors/synopsys/verilog_dv_tb_runtime_args.f.template
> -{DPI_LIBS}
@jmlemay99 why is this no longer necessary? How are the DPI libs getting into VCS without this?

2022-10-18 04:17 UTC, ciglass commented on verilog/private/dv.bzl
> +        "_default_sim_opts_xrun": attr.label(
Why do we still need _default_sim_opts_xrun and _vcs?

2022-10-20 00:49 UTC, jmlemay99 commented on vendors/cadence/verilog_dv_tb_compile_args.f.template
> +-sv
@ciglass they're not really new flags.  They are static flags that formerly existed in simmer's COMPILE_TEMPLATE.  Since simmer is now part of rules_verilog, and rules_verilog has a place for static compiler args, the move seemed intuitive to me.  Let the vendor-specific template files handle the static flags, and let simmer handle the dynamic flags.

2022-10-20 00:50 UTC, jmlemay99 commented on vendors/synopsys/verilog_dv_default_sim_opts.f
> +-full64
@ciglass, see response above.

There are fewer additions here because VCS only allows certain flags in an flist.  Xrun allows any flag in an flist.

2022-10-20 00:51 UTC, jmlemay99 commented on vendors/synopsys/verilog_dv_tb_runtime_args.f.template
> -{DPI_LIBS}
@ciglass, I think this was an accidental omission by me, and a good catch by you.  I will add it back.

2022-10-20 00:53 UTC, jmlemay99 commented on vendors/synopsys/verilog_dv_tb_compile_args.f.template
> +-sverilog
@ciglass, same response as above.  :)

2022-10-20 01:06 UTC, jmlemay99 commented on verilog/private/dv.bzl
> +        "_default_sim_opts_xrun": attr.label(
@ciglass, because my PR introduces vendor-specific default sim opts templates.

For all of these templates used by rules_verilog, I tried to use common templates where possible, and only use vendor-specific templates where necessary.

2022-10-20 02:36 UTC, ciglass commented on vendors/synopsys/verilog_dv_tb_runtime_args.f.template
> -{DPI_LIBS}
Gotcha. If we need to split those out again in the future, it seems like it would be a straightforward change to point to vendor-specific versions again.

2022-10-20 02:39 UTC, ciglass commented on verilog/private/dv.bzl
> +        "_default_sim_opts_xrun": attr.label(
I think I understand. Is it correct to say that we want rules_verilog to be able to statically render both the xrun and vcs flists using the same verilog_dv_tb targets because of the (internal) Lightelligence tool setup? If we didn't have that restriction on rules_verilog, could we instead have a single (instead of per-vendor) default_sim_opts and  compile_args_template that would statically point to the right template?

2022-10-20 17:19 UTC, jmlemay99 commented on verilog/private/dv.bzl
> +        "_default_sim_opts_xrun": attr.label(
**"Is it correct to say that we want rules_verilog to be able to statically render both the xrun and vcs flists using the same verilog_dv_tb targets because of the (internal) Lightelligence tool setup?"**
Yes and no.  Yes we use both VCS and XRUN at Lightelligence.  But the real reason to statically render both files is because there's no way for the user to pass their intent to bazel.  I can't say "render me the xrun sim opts file only".   Nor can I say "render me a common sim opts file whose contents change dynamically based on my intended simulator".

2022-10-20 18:22 UTC, jmlemay99 commented on vendors/synopsys/verilog_dv_tb_runtime_args.f.template
> -{DPI_LIBS}
Yep.  Agreed.

2022-10-21 15:12 UTC, ciglass commented on verilog/private/dv.bzl
> +        "_default_sim_opts_xrun": attr.label(
I see your point. We could instead have single attributes for `_default_sim_opts` and `_default_compile_args`, and require that a project that wants to use both VCS and XRUN instantiate two `verilog_dv_tb` targets, one for VCS and one for XRUN, each with different attributes passed in. The major downside is that it makes testbench naming and discovery less intuitive.

I'll file an issue with more details.

2022-10-21 15:13 UTC, ciglass approved these changes

2022-10-21 15:15 UTC, merged